import os

SERVICE_NAME = os.environ.get('SERVICE_NAME', '')
SERVICE_STAGE = os.environ.get('SERVICE_STAGE', '')
SERVICE_ROUTE = os.environ.get('SERVICE_ROUTE', '')

PROPAGATE_EXCEPTIONS = True

# SIEVE
SIEVE_ERROR_CODE = 'TRI0001'
SIEVE_RESPONSE_MESSAGE = 'INVALID_REQUEST'
